lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  
theme: minima # Built-in Jekyll theme name
title: "My SysAdmin Project's Documentation"
description: "A detailed overview of my Arch Linux/Docker projects"